import { PrismaClient } from "@prisma/client";
const prisma = new PrismaClient();

const companies = [
  {
    name: "당근마켓",
    description: "지역 기반 중고거래 플랫폼",
    category: "커뮤니티",
    realInvestmentAmount: 288,
    revenue: 24,
    numberOfEmployees: 323,
  },
  {
    name: "무브글로벌",
    description: "동남아에서 K-패션을 판매하는 커머스 스타트업",
    category: "이커머스",
    realInvestmentAmount: 219,
    revenue: 155,
    numberOfEmployees: 252,
  },
  {
    name: "트위니",
    description: "자율주행 로봇 기반 물류 이동 솔루션",
    category: "로보틱스",
    realInvestmentAmount: 235,
    revenue: 134,
    numberOfEmployees: 393,
  },
  {
    name: "리하인드시스템즈",
    description: "웹툰 작가를 위한 제작 및 유통 플랫폼",
    category: "콘텐츠",
    realInvestmentAmount: 256,
    revenue: 4,
    numberOfEmployees: 297,
  },
  {
    name: "리하인드코리아",
    description: "웹툰 작가를 위한 제작 및 유통 플랫폼",
    category: "콘텐츠",
    realInvestmentAmount: 57,
    revenue: 61,
    numberOfEmployees: 412,
  },
  {
    name: "두브레인파워",
    description: "발달 지연 아동을 위한 AI 기반 두뇌 발달 솔루션",
    category: "헬스케어",
    realInvestmentAmount: 264,
    revenue: 139,
    numberOfEmployees: 34,
  },
  {
    name: "브레인커머스글로벌",
    description: "AI로 상품 트렌드를 분석하는 솔루션",
    category: "AI",
    realInvestmentAmount: 242,
    revenue: 171,
    numberOfEmployees: 420,
  },
  {
    name: "루닛",
    description: "의료 영상 분석 AI 솔루션",
    category: "헬스케어",
    realInvestmentAmount: 151,
    revenue: 91,
    numberOfEmployees: 50,
  },
  {
    name: "클라썸코리아",
    description: "쌍방향 소통이 가능한 교육 플랫폼",
    category: "에듀테크",
    realInvestmentAmount: 203,
    revenue: 13,
    numberOfEmployees: 151,
  },
  {
    name: "에이슬립테크",
    description: "AI 기반 수면 데이터 분석 및 개선 솔루션",
    category: "헬스케어",
    realInvestmentAmount: 134,
    revenue: 128,
    numberOfEmployees: 127,
  },
  {
    name: "루닛파워",
    description: "의료 영상 분석 AI 솔루션",
    category: "헬스케어",
    realInvestmentAmount: 263,
    revenue: 116,
    numberOfEmployees: 353,
  },
  {
    name: "리하인드테크",
    description: "웹툰 작가를 위한 제작 및 유통 플랫폼",
    category: "콘텐츠",
    realInvestmentAmount: 80,
    revenue: 69,
    numberOfEmployees: 72,
  },
  {
    name: "에이슬립인터랙티브",
    description: "AI 기반 수면 데이터 분석 및 개선 솔루션",
    category: "헬스케어",
    realInvestmentAmount: 63,
    revenue: 149,
    numberOfEmployees: 65,
  },
  {
    name: "직토코리아",
    description: "보험 추천 및 맞춤 설계 플랫폼",
    category: "핀테크",
    realInvestmentAmount: 188,
    revenue: 13,
    numberOfEmployees: 112,
  },
  {
    name: "에어클래스시스템즈",
    description: "전문가 실시간 화상 강의 플랫폼",
    category: "에듀테크",
    realInvestmentAmount: 253,
    revenue: 103,
    numberOfEmployees: 492,
  },
  {
    name: "마인즈랩파워",
    description: "AI 기술을 활용한 고객 응대 자동화 솔루션",
    category: "AI",
    realInvestmentAmount: 242,
    revenue: 148,
    numberOfEmployees: 458,
  },
  {
    name: "에이슬립소프트",
    description: "AI 기반 수면 데이터 분석 및 개선 솔루션",
    category: "헬스케어",
    realInvestmentAmount: 18,
    revenue: 143,
    numberOfEmployees: 356,
  },
  {
    name: "무브시스템즈",
    description: "동남아에서 K-패션을 판매하는 커머스 스타트업",
    category: "이커머스",
    realInvestmentAmount: 193,
    revenue: 62,
    numberOfEmployees: 472,
  },
  {
    name: "직토테크",
    description: "보험 추천 및 맞춤 설계 플랫폼",
    category: "핀테크",
    realInvestmentAmount: 255,
    revenue: 127,
    numberOfEmployees: 120,
  },
  {
    name: "마인즈랩코리아",
    description: "AI 기술을 활용한 고객 응대 자동화 솔루션",
    category: "AI",
    realInvestmentAmount: 235,
    revenue: 170,
    numberOfEmployees: 373,
  },
  {
    name: "두브레인테크",
    description: "발달 지연 아동을 위한 AI 기반 두뇌 발달 솔루션",
    category: "헬스케어",
    realInvestmentAmount: 245,
    revenue: 82,
    numberOfEmployees: 474,
  },
  {
    name: "루닛랩스",
    description: "의료 영상 분석 AI 솔루션",
    category: "헬스케어",
    realInvestmentAmount: 166,
    revenue: 105,
    numberOfEmployees: 318,
  },
  {
    name: "직방소프트",
    description: "부동산 정보 플랫폼",
    category: "프롭테크",
    realInvestmentAmount: 88,
    revenue: 149,
    numberOfEmployees: 194,
  },
  {
    name: "해피문데이시스템즈",
    description: "여성 건강 관리 구독 서비스",
    category: "헬스케어",
    realInvestmentAmount: 220,
    revenue: 29,
    numberOfEmployees: 464,
  },
  {
    name: "비트센싱테크",
    description: "레이다 기반 스마트 센서 솔루션 기업",
    category: "딥테크",
    realInvestmentAmount: 230,
    revenue: 141,
    numberOfEmployees: 152,
  },
  {
    name: "오늘의집인터랙티브",
    description: "인테리어 커머스 및 콘텐츠 플랫폼",
    category: "라이프스타일",
    realInvestmentAmount: 174,
    revenue: 133,
    numberOfEmployees: 102,
  },
  {
    name: "토스랩랩스",
    description: "업무용 메신저 ‘잔디’ 개발사",
    category: "B2B SaaS",
    realInvestmentAmount: 109,
    revenue: 184,
    numberOfEmployees: 298,
  },
  {
    name: "트위니파워",
    description: "자율주행 로봇 기반 물류 이동 솔루션",
    category: "로보틱스",
    realInvestmentAmount: 193,
    revenue: 104,
    numberOfEmployees: 232,
  },
  {
    name: "오늘의집글로벌",
    description: "인테리어 커머스 및 콘텐츠 플랫폼",
    category: "라이프스타일",
    realInvestmentAmount: 242,
    revenue: 100,
    numberOfEmployees: 95,
  },
  {
    name: "트위니스튜디오",
    description: "자율주행 로봇 기반 물류 이동 솔루션",
    category: "로보틱스",
    realInvestmentAmount: 261,
    revenue: 115,
    numberOfEmployees: 92,
  },
  {
    name: "에어클래스코리아",
    description: "전문가 실시간 화상 강의 플랫폼",
    category: "에듀테크",
    realInvestmentAmount: 40,
    revenue: 8,
    numberOfEmployees: 466,
  },
  {
    name: "에어클래스파워",
    description: "전문가 실시간 화상 강의 플랫폼",
    category: "에듀테크",
    realInvestmentAmount: 111,
    revenue: 59,
    numberOfEmployees: 230,
  },
  {
    name: "리하인드파워",
    description: "웹툰 작가를 위한 제작 및 유통 플랫폼",
    category: "콘텐츠",
    realInvestmentAmount: 150,
    revenue: 149,
    numberOfEmployees: 452,
  },
  {
    name: "직방글로벌",
    description: "부동산 정보 플랫폼",
    category: "프롭테크",
    realInvestmentAmount: 113,
    revenue: 122,
    numberOfEmployees: 429,
  },
  {
    name: "직방랩스",
    description: "부동산 정보 플랫폼",
    category: "프롭테크",
    realInvestmentAmount: 5,
    revenue: 83,
    numberOfEmployees: 452,
  },
  {
    name: "비트센싱랩스",
    description: "레이다 기반 스마트 센서 솔루션 기업",
    category: "딥테크",
    realInvestmentAmount: 197,
    revenue: 57,
    numberOfEmployees: 449,
  },
  {
    name: "당근마켓",
    description: "지역 기반 중고거래 플랫폼",
    category: "커뮤니티",
    realInvestmentAmount: 153,
    revenue: 7,
    numberOfEmployees: 453,
  },
  {
    name: "두브레인글로벌",
    description: "발달 지연 아동을 위한 AI 기반 두뇌 발달 솔루션",
    category: "헬스케어",
    realInvestmentAmount: 164,
    revenue: 123,
    numberOfEmployees: 172,
  },
  {
    name: "해피문데이스튜디오",
    description: "여성 건강 관리 구독 서비스",
    category: "헬스케어",
    realInvestmentAmount: 56,
    revenue: 122,
    numberOfEmployees: 74,
  },
  {
    name: "에이슬립",
    description: "AI 기반 수면 데이터 분석 및 개선 솔루션",
    category: "헬스케어",
    realInvestmentAmount: 73,
    revenue: 124,
    numberOfEmployees: 136,
  },
  {
    name: "에어클래스스튜디오",
    description: "전문가 실시간 화상 강의 플랫폼",
    category: "에듀테크",
    realInvestmentAmount: 290,
    revenue: 50,
    numberOfEmployees: 29,
  },
  {
    name: "비트센싱스튜디오",
    description: "레이다 기반 스마트 센서 솔루션 기업",
    category: "딥테크",
    realInvestmentAmount: 238,
    revenue: 70,
    numberOfEmployees: 115,
  },
  {
    name: "브레인커머스스튜디오",
    description: "AI로 상품 트렌드를 분석하는 솔루션",
    category: "AI",
    realInvestmentAmount: 195,
    revenue: 198,
    numberOfEmployees: 158,
  },
  {
    name: "아자스쿨테크",
    description: "초·중·고 대상의 학습 멘토링 플랫폼",
    category: "에듀테크",
    realInvestmentAmount: 174,
    revenue: 150,
    numberOfEmployees: 139,
  },
  {
    name: "루닛스튜디오",
    description: "의료 영상 분석 AI 솔루션",
    category: "헬스케어",
    realInvestmentAmount: 123,
    revenue: 131,
    numberOfEmployees: 335,
  },
  {
    name: "비트센싱인터랙티브",
    description: "레이다 기반 스마트 센서 솔루션 기업",
    category: "딥테크",
    realInvestmentAmount: 9,
    revenue: 122,
    numberOfEmployees: 218,
  },
  {
    name: "두브레인스튜디오",
    description: "발달 지연 아동을 위한 AI 기반 두뇌 발달 솔루션",
    category: "헬스케어",
    realInvestmentAmount: 138,
    revenue: 152,
    numberOfEmployees: 450,
  },
  {
    name: "비트센싱글로벌",
    description: "레이다 기반 스마트 센서 솔루션 기업",
    category: "딥테크",
    realInvestmentAmount: 68,
    revenue: 79,
    numberOfEmployees: 380,
  },
  {
    name: "트위니글로벌",
    description: "자율주행 로봇 기반 물류 이동 솔루션",
    category: "로보틱스",
    realInvestmentAmount: 263,
    revenue: 170,
    numberOfEmployees: 61,
  },
  {
    name: "버즈빌소프트",
    description: "잠금 화면 광고 플랫폼",
    category: "애드테크",
    realInvestmentAmount: 115,
    revenue: 160,
    numberOfEmployees: 36,
  },
];

async function main() {
  await prisma.company.createMany({
    data: companies,
  });
}

main()
  .then(async () => {
    await prisma.$disconnect();
  })
  .catch(async (e) => {
    console.error(e);
    await prisma.$disconnect();
    process.exit(1);
  });
